'use strict';
let news1 = `<p>1. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus asperiores beatae dolorum ullam. Accusamus animi asperiores commodi distinctio earum esse est excepturi impedit ipsa laborum magni, mollitia nemo nobis odio quasi qui, rem repellendus. Aperiam cumque eius est facere illo laboriosam magnam maxime modi officia pariatur placeat, quae, repudiandae rerum sed veniam. Consectetur dicta doloremque eius expedita illo itaque quasi tempore! Ab aut mollitia pariatur, provident quas quo. Ad aliquid, atque blanditiis culpa ducimus esse est excepturi expedita in odio odit, omnis porro ratione sequi tempora ullam vitae voluptas. Debitis dolore iste mollitia placeat rerum! Laborum praesentium ratione reiciendis unde? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem consequatur culpa cum dolor dolorem dolorum est eveniet ex exercitationem facilis fugiat inventore ipsa ipsam ipsum laudantium, magnam mollitia natus, odit perferendis quae quam quia quis repellendus sequi temporibus ullam vero voluptatum? Est magnam nulla quasi quo tempora!</p>`;
let news2 = `<p>2. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae cumque excepturi harum odio odit ut voluptate. Beatae debitis eveniet ex ipsum quae ut? Enim maxime minima molestias, non quia quisquam quod suscipit tempora tempore voluptates. Beatae consequuntur, debitis distinctio eius eum, facere id illum incidunt neque odit placeat veritatis, voluptatibus! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem consequatur culpa cum dolor dolorem dolorum est eveniet ex exercitationem facilis fugiat inventore ipsa ipsam ipsum laudantium, magnam mollitia natus, odit perferendis quae quam quia quis repellendus sequi temporibus ullam vero voluptatum? Est magnam nulla quasi quo tempora!</p>`;
let news3 = `<p>3. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur ea libero quaerat repudiandae sapiente. Accusamus alias aliquam at beatae blanditiis consequatur consequuntur culpa dolore doloremque excepturi explicabo facilis illo inventore itaque labore laboriosam laudantium minus modi nam omnis possimus praesentium, quaerat quas quasi quod recusandae rerum sint totam unde vel, velit vero voluptates voluptatum. Alias aliquam aliquid cumque expedita quisquam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem consequatur culpa cum dolor dolorem dolorum est eveniet ex exercitationem facilis fugiat inventore ipsa ipsam ipsum laudantium, magnam mollitia natus, odit perferendis quae quam quia quis repellendus sequi temporibus ullam vero voluptatum? Est magnam nulla quasi quo tempora!</p>`;
let news4 = `<p>4. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur ea libero quaerat repudiandae sapiente. Accusamus alias aliquam at beatae blanditiis consequatur consequuntur culpa dolore doloremque excepturi explicabo facilis illo inventore itaque labore laboriosam laudantium minus modi nam omnis possimus praesentium, quaerat quas quasi quod recusandae rerum sint totam unde vel, velit vero voluptates voluptatum. Alias aliquam aliquid cumque expedita quisquam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem consequatur culpa cum dolor dolorem dolorum est eveniet ex exercitationem facilis fugiat inventore ipsa ipsam ipsum laudantium, magnam mollitia natus, odit perferendis quae quam quia quis repellendus sequi temporibus ullam vero voluptatum? Est magnam nulla quasi quo tempora!</p>`;
let news5 = `<p>5. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur ea libero quaerat repudiandae sapiente. Accusamus alias aliquam at beatae blanditiis consequatur consequuntur culpa dolore doloremque excepturi explicabo facilis illo inventore itaque labore laboriosam laudantium minus modi nam omnis possimus praesentium, quaerat quas quasi quod recusandae rerum sint totam unde vel, velit vero voluptates voluptatum. Alias aliquam aliquid cumque expedita quisquam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem consequatur culpa cum dolor dolorem dolorum est eveniet ex exercitationem facilis fugiat inventore ipsa ipsam ipsum laudantium, magnam mollitia natus, odit perferendis quae quam quia quis repellendus sequi temporibus ullam vero voluptatum? Est magnam nulla quasi quo tempora!</p>`;
let news6 = `<p>6. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur ea libero quaerat repudiandae sapiente. Accusamus alias aliquam at beatae blanditiis consequatur consequuntur culpa dolore doloremque excepturi explicabo facilis illo inventore itaque labore laboriosam laudantium minus modi nam omnis possimus praesentium, quaerat quas quasi quod recusandae rerum sint totam unde vel, velit vero voluptates voluptatum. Alias aliquam aliquid cumque expedita quisquam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem consequatur culpa cum dolor dolorem dolorum est eveniet ex exercitationem facilis fugiat inventore ipsa ipsam ipsum laudantium, magnam mollitia natus, odit perferendis quae quam quia quis repellendus sequi temporibus ullam vero voluptatum? Est magnam nulla quasi quo tempora!</p>`;
let news7 = `<p>7. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur ea libero quaerat repudiandae sapiente. Accusamus alias aliquam at beatae blanditiis consequatur consequuntur culpa dolore doloremque excepturi explicabo facilis illo inventore itaque labore laboriosam laudantium minus modi nam omnis possimus praesentium, quaerat quas quasi quod recusandae rerum sint totam unde vel, velit vero voluptates voluptatum. Alias aliquam aliquid cumque expedita quisquam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem consequatur culpa cum dolor dolorem dolorum est eveniet ex exercitationem facilis fugiat inventore ipsa ipsam ipsum laudantium, magnam mollitia natus, odit perferendis quae quam quia quis repellendus sequi temporibus ullam vero voluptatum? Est magnam nulla quasi quo tempora!</p>`;
let news8 = `<p>8. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur ea libero quaerat repudiandae sapiente. Accusamus alias aliquam at beatae blanditiis consequatur consequuntur culpa dolore doloremque excepturi explicabo facilis illo inventore itaque labore laboriosam laudantium minus modi nam omnis possimus praesentium, quaerat quas quasi quod recusandae rerum sint totam unde vel, velit vero voluptates voluptatum. Alias aliquam aliquid cumque expedita quisquam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem consequatur culpa cum dolor dolorem dolorum est eveniet ex exercitationem facilis fugiat inventore ipsa ipsam ipsum laudantium, magnam mollitia natus, odit perferendis quae quam quia quis repellendus sequi temporibus ullam vero voluptatum? Est magnam nulla quasi quo tempora!</p>`;
let news9 = `<p>9. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur ea libero quaerat repudiandae sapiente. Accusamus alias aliquam at beatae blanditiis consequatur consequuntur culpa dolore doloremque excepturi explicabo facilis illo inventore itaque labore laboriosam laudantium minus modi nam omnis possimus praesentium, quaerat quas quasi quod recusandae rerum sint totam unde vel, velit vero voluptates voluptatum. Alias aliquam aliquid cumque expedita quisquam? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid asperiores assumenda autem consequatur culpa cum dolor dolorem dolorum est eveniet ex exercitationem facilis fugiat inventore ipsa ipsam ipsum laudantium, magnam mollitia natus, odit perferendis quae quam quia quis repellendus sequi temporibus ullam vero voluptatum? Est magnam nulla quasi quo tempora!</p>`;
let arr = [news1, news2, news3, news4, news5, news6, news7, news8, news9];
let counter = arr.length;
let spiner = document.querySelector('#spiner');


window.addEventListener("scroll", function(){

    let block = document.querySelector('.newsContainer');

    let contentHeight = block.offsetHeight; //высота блока контента вместе с границами
    let yOffset       = window.pageYOffset; // текущее положение скролбара
    let window_height = window.innerHeight; // высота внутренней области окна документа
    let y = yOffset + window_height;
    if(y >= contentHeight && counter > 0)
    {
        block.insertAdjacentHTML("beforeend", arr[arr.length-counter]);
        counter--;
        // обсудить как сделать чтобы работало с таймаутом для проверки работы спинера
        // spiner.classList.add('lds-ellipsis');
        //     // setTimeout(()=> {
        //         block.insertAdjacentHTML("beforeend", newsAll[acc]);
        //         spiner.classList.remove('lds-ellipsis');
        //         acc++;
        //     // }, 1000);
    }

});